context:
  name: crane
  version: "0.21.5"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/google/go-containerregistry/archive/refs/tags/v${{ version }}.tar.gz
  sha256: c2291876a087f93a61b561594a389e6543091c0c5c50f16b5f9c14417d2fc947

build:
  number: 0
  script:
    - if: not win
      then: go build -v -ldflags "-w -s -X github.com/google/go-containerregistry/cmd/crane/cmd.Version=${{ version }}" -o $PREFIX/bin/crane ./cmd/crane
      else: go install -v -ldflags "-w -s -X github.com/google/go-containerregistry/cmd/crane/cmd.Version=${{ version }}" ./cmd/crane
    - go-licenses save ./cmd/crane --save_path=./license-files

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - crane version

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: A tool for interacting with remote OCI images and registries.
  homepage: https://github.com/google/go-containerregistry/tree/main/cmd/crane

extra:
  recipe-maintainers:
    - benmoss
